name: Grader Verification
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f2007156@ds.study.iitm.ac.in
        run: echo "Hello, world!"
